apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pozoledf-sample-app

images:
- name: registry.mycompany.com/pozoledf-sample-app
  newName: registry.mycompany.com/pozoledf-sample-app
  newTag: v1.0

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
