apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: pozoledf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.mycompany.com/pozoledf-sample-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      # Comment this if not needed
      imagePullSecrets:
      - name: regcred
