apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pozoledf

images:
- name: registry.mycompany.com/pozoledf-sample-app
  newName: pozoledf.azurecr.io/pozoledf-sample-app
  newTag: 1.0.9

resources:
- namespace.yml
- deployment.yml
- service.yml
