apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pozoledf

images:
- name: registry.mycompany.com/pozoledf-sample-app
  newName: 089964607376.dkr.ecr.us-west-2.amazonaws.com/pozoledf-sample-app
  newTag: 1.0.8

resources:
- namespace.yml
- deployment.yml
- service.yml
