apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pozoledf-sample-app

images:
- name: registry.mycompany.com/pozoledf-sample-app
  newName: 089964607376.dkr.ecr.us-west-2.amazonaws.com/pozoledf-sample-app
  newTag: 1.0.52

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
